function event = EventLogger(varargin)
%EVENTLOGGER Create one standard event-log entry.
% Supports the Stage 16 wind-trip schema and the older 8-argument helper
% shape used by existing protection prototypes.

if nargin == 10
    time_s = varargin{1};
    event_type = varargin{2};
    target_type = varargin{3};
    target_id = varargin{4};
    measured_value = varargin{5};
    threshold = varargin{6};
    delay_s = varargin{7};
    action = varargin{8};
    source_protection = varargin{9};
    description = varargin{10};
elseif nargin == 8
    time_s = varargin{1};
    event_type = varargin{2};
    target_type = 'component';
    target_id = varargin{3};
    measured_value = varargin{4};
    threshold = varargin{5};
    delay_s = varargin{6};
    action = varargin{7};
    source_protection = '';
    description = varargin{8};
else
    error('EventLogger:InvalidInput', 'Expected 8 or 10 input arguments.');
end

event = struct( ...
    'time_s', double(time_s), ...
    'event_type', char(event_type), ...
    'target_type', char(target_type), ...
    'target_id', char(target_id), ...
    'measured_value', double(measured_value), ...
    'threshold', double(threshold), ...
    'delay_s', double(delay_s), ...
    'action', char(action), ...
    'source_protection', char(source_protection), ...
    'description', char(description), ...
    'pscad_offline_feedback', false, ...
    'component_id', char(target_id), ...
    'trigger_value', double(measured_value), ...
    'command', char(action), ...
    'notes', char(description));
end
