function event = EventLogger(time_s, event_type, component_id, trigger_value, threshold, delay_s, command, notes)
%EVENTLOGGER Create one standard event-log entry.
event = struct( ...
    'time_s', double(time_s), ...
    'event_type', string(event_type), ...
    'component_id', string(component_id), ...
    'trigger_value', double(trigger_value), ...
    'threshold', double(threshold), ...
    'delay_s', double(delay_s), ...
    'command', string(command), ...
    'notes', string(notes));
end

