function cases = export_offline_trip_cases(voltageTraceCsv, outputCaseCsv, caseId, noTripTime_s)
%EXPORT_OFFLINE_TRIP_CASES Convert MATLAB VRT decisions to PSCAD trip cases.
% The voltage trace must use wind order WF33, WF35, WF38. If no trace is
% provided, a small deterministic smoke trace is generated.

if nargin < 1 || isempty(voltageTraceCsv)
    voltageTraceCsv = '';
end
if nargin < 2 || isempty(outputCaseCsv)
    outputCaseCsv = fullfile('config', 'offline_trip_cases_from_matlab.csv');
end
if nargin < 3 || isempty(caseId)
    caseId = 'matlab_vrt_demo_50ms_delayed';
end
if nargin < 4 || isempty(noTripTime_s)
    noTripTime_s = 99.0;
end

root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(root, 'matlab'));

trace = loadTrace(voltageTraceCsv);
settings = default_protection_settings();
state = [];
online = true(3, 1);
tripTimes = nan(3, 1);

for i = 1:height(trace)
    t = trace.time_s(i);
    if i == 1
        dt = 0;
    else
        dt = trace.time_s(i) - trace.time_s(i - 1);
    end

    obs = struct();
    obs.wind_pcc_voltage_pu = [trace.wf33_v_pu(i); trace.wf35_v_pu(i); trace.wf38_v_pu(i)];
    obs.wind_active_power_MW = [632; 650; 830];
    obs.wind_online = online;
    obs.simulation_time_s = t;
    obs.interface_dt_s = dt;

    [cmd, state] = pscad_cascade_step(t, dt, obs, state, settings);
    newlyTripped = cmd.wind_disconnect_cmd(:) & online;
    tripTimes(newlyTripped) = t;
    online(newlyTripped) = false;
end

tripTimes(isnan(tripTimes)) = noTripTime_s;

cases = table( ...
    string(caseId), ...
    tripTimes(3), ...
    tripTimes(2), ...
    tripTimes(1), ...
    "Generated by MATLAB offline VRT protection export.", ...
    'VariableNames', {'case_id', 'wf38_trip_time_s', 'wf35_trip_time_s', 'wf33_trip_time_s', 'notes'});

outDir = fileparts(outputCaseCsv);
if ~isempty(outDir) && ~isfolder(outDir)
    mkdir(outDir);
end
writetable(cases, outputCaseCsv);
end

function trace = loadTrace(voltageTraceCsv)
if ~isempty(voltageTraceCsv)
    trace = readtable(voltageTraceCsv);
    required = {'time_s', 'wf33_v_pu', 'wf35_v_pu', 'wf38_v_pu'};
    missing = setdiff(required, trace.Properties.VariableNames);
    if ~isempty(missing)
        error('export_offline_trip_cases:MissingColumns', ...
            'Voltage trace is missing columns: %s', strjoin(missing, ', '));
    end
    return
end

time_s = (0:0.01:5).';
wf33_v_pu = ones(size(time_s));
wf35_v_pu = ones(size(time_s));
wf38_v_pu = ones(size(time_s));
wf38_v_pu(time_s >= 0.62) = 0.10;
wf35_v_pu(time_s >= 0.72) = 0.10;
wf33_v_pu(time_s >= 0.82) = 0.10;
trace = table(time_s, wf33_v_pu, wf35_v_pu, wf38_v_pu);
end
